# Configuration to create s3 connections
s3:
  access_key: ''
  secret_key: ''
  src_endpoint_url: 'https://s3.amazonaws.com'
  src_bucket: 'xetra-src-data-rn23'
  trg_endpoint_url: 'https://s3.amazonaws.com'
  trg_bucket: 'xetra-trg-data-rn23'
  AWS_s3_conn: 'AWS_s3_conn'


# Configuration specific to the source
source:
  src_first_extract_date: '2022-01-3'
  src_columns: ['ISIN', 'Mnemonic', 'Date', 'Time', 'StartPrice', 'EndPrice', 'MinPrice', 'MaxPrice', 'TradedVolume']
  src_col_date: 'Date'
  src_col_isin: 'ISIN'
  src_col_time: 'Time'
  src_col_min_price: 'MinPrice'
  src_col_start_price: 'StartPrice'
  src_col_max_price: 'MaxPrice'
  src_col_traded_vol: 'TradedVolume'

# configuration specific to the target
target:
  trg_key: 'report1/xetra_daily_report1_'
  trg_columns: ['ISIN', 'Mnemonic','SecurityDesc','SecurityType','SecurityID','Currency', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice', 'EndPrice','TradedVolume','NumberOfTrades']
  trg_key_date_format: '%Y%m%d_%H%M%S'
  trg_format: 'parquet'
  trg_col_isin: 'isin'
  trg_col_date: 'date'
  trg_col_op_price: 'opening_price_eur'
  trg_col_clos_price: 'closing_price_eur'
  trg_col_min_price: 'minimum_price_eur'
  trg_col_max_price: 'maximum_price_eur'
  trg_col_dail_trad_vol: 'daily_traded_volume'
  trg_col_ch_prev_clos: 'change_prev_closing_%'

# configuration specific to the meta file
meta:
  meta_key: 'meta-xetra/meta_file.csv'

db:
  host: 'localhost'
  login: 'root'
  password: 'root'
  port: '3306'
  database: ''
  schema: 'transactions'

# Logging configuration
logging:
  version: 1
  formatters:
    xetra:
      format: "Xetra Transformer - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: xetra
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]